version: 2

sources:
    - name: raw
      description: This is a replica of the Postgres database used by our app
      database: analytics
      schema: raw
      tables:
          - name: customers
            description: One record per customer.
          - name: orders
            description: One record per order. Includes cancelled and deleted orders.
          - name: stripe_payments
            description: One record per payment. Includes transactions with total amount's as zero.