version: 2

sources:
    - name: raw
      description: This is a replica of the Postgres database used by our app
      database: analytics
      schema: raw
      tables:
          - name: customers
            description: Raw customers data.
            columns:
              - name: id
                description: Primary key
                tests:
                  - unique
                  - not_null    
          - name: orders
            description: Raw orders data. One record per order. Includes cancelled and deleted orders.
            columns:
              - name: id
                description: Primary key
                tests:
                  - unique
                  - not_null 
          - name: stripe_payments
            description: Payment. Includes transactions with total amount's as zero.
            loaded_at_field: _batched_at
            freshness: 
              warn_after: {count: 12, period: hour}
              error_after: {count: 24, period: hour}

            